# https://taskfile.dev makefile commands. Requires installed taskfile for functionality
# useful commands during development
# run `task --list-all` to list all available commands
version: "3"

tasks:
  cluster:create:
    desc: create kind cluster for testing. Plugin is tested in Kind cluster and microk8s
    cmds:
      - kind create cluster
    
  cluster:scan:
    desc: >
      Kind cluster for usage with argocd, needs fixed ~/.kube/config cluster server address
      to address received in this command
      open ~/.kube/config and change cluster IP to discovered from command
    cmds:
      - kubectl get endpoints

  argo:password:
    desc: >
      port forward `kubectl port-forward svc/argocd-server -n argocd 8080:443`
      and login with `admin` and password from this command
    cmds:
      - argocd admin initial-password -n argocd

  argo:deploy:
    desc: deploy argocd with cue plugin
    cmds:
      - kubectl apply -k ./plugin

  argo:delete:
    cmds:
      - kubectl delete -k ./plugin

  argo:apply:
    desc: try deploying cue application
    cmds:
      - kubectl apply -f ./application
