# https://taskfile.dev makefile commands. Requires installed taskfile for functionality
# useful commands during development
# run `task --list-all` to list all available commands
version: "3"

tasks:
  cluster:create:
    desc: create kind cluster for testing. Plugin is tested in Kind cluster and microk8s
    cmds:
      - kind create cluster
    
  cluster:scan:
    desc: >
      Kind cluster for usage with argocd, needs fixed ~/.kube/config cluster server address
      to address received in this command
      open ~/.kube/config and change cluster IP to discovered from command
    cmds:
      - kubectl get endpoints

  argo:password:
    desc: >
      port forward `kubectl port-forward svc/argocd-server -n argocd 8080:443`
      and login with `admin` and password from this command
    cmds:
      - argocd admin initial-password -n argocd

  argo:deploy:
    desc: deploy argocd with cue plugin
    cmds:
      - kubectl apply -k ./plugin

  argo:delete:
    cmds:
      - kubectl delete -k ./plugin

  argo:apply:
    desc: try deploying cue application
    cmds:
      - kubectl apply -f ./examples/applications

  app:test:
    cmds:
      - go test ./argocue -coverprofile=cover.out {{.CLI_ARGS}}

  app:build:
    cmds:
      - CGO_ENABLED=0 go build -v -o main main.go
      - sudo rm /usr/local/bin/argocue
      - sudo ln -s $(pwd)/main /usr/local/bin/argocue

  docker:build:
    cmds:
      - docker build --tag darkwind8/argocue:${tag_version}-amd64 .

  docker:build:arm:
    # ubuntu 22.04 amd64: sudo apt install -y qemu-user-static binfmt-support
    cmds:
      - docker buildx build --platform linux/arm64 --tag darkwind8/argocue:${tag_version}-arm64 .

  docker:push:
    cmds:
      - docker push darkwind8/argocue:${tag_version}-amd64

  docker:buildpush:
    cmds:
      - task: docker:build
      - task: docker:push

  docker:buildpusharchs:
    cmds:
      - task: docker:build
      - task: docker:build:arm
      - task: docker:push
      - docker push darkwind8/argocue:${tag_version}-arm64
      - >
        docker manifest create
        darkwind8/argocue:${tag_version}
        --amend darkwind8/argocue:${tag_version}-amd64
        --amend darkwind8/argocue:${tag_version}-arm64
      - docker manifest push darkwind8/argocue:${tag_version}

env:
  tag_version: v0.3.0-a3
